# HLint configuration file
##########################

- functions:
  - {name: head, within: [Sequence]} # head can only appear in no modules
  - {name: tail, within: []} 
  - {name: Maybe.fromJust, within: []} 

- ignore: {name: "Use head"}
- ignore: {name: "Use lambda-case"}
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Use asum"}
- ignore: {name: "Reduce duplication"}
- ignore: {name: "Use $>"}
